  - name: install maven
    import_role:
      name: common
      import_from: maven_setup

  - name: configure the app setup
    import_role:
      name: common
      import_from: app_setup

  - name: systemd setup
    import_role:
      name: common
      import_from: systemd_setup

  - name: install python dependencies
    pip:
      name: PyMySQL
      executable: pip3.9

  - name: load mysql data
    community.mysql.mysql_db:
      state: import
      name: all
      login_user: root
      login_password: "{{ MYSQL_PASSWORD }}"
      login_host: "{{ MYSQL_HOST }}"
      target: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql

  - name: enable and start shipping
    service:
      name: shipping
      state: restarted
      enabled: yes