# ansible-playbook roboshop.yaml -e "component=mongodb"
- name: configure "{{ component }}" server
  hosts: "{{ component }}"
  become: yes
  roles:
  - "{{ component }}"



  # execute all at a time by passing in CMD

  ansible-playbook -e "component=mongodb" roboshop.yaml
  ansible-playbook -e "component=mysql" roboshop.yaml
  ansible-playbook -e "component=redis" roboshop.yaml
  ansible-playbook -e "component=rabitmq" roboshop.yaml
  ansible-playbook -e "component=catalogue" roboshop.yaml
  ansible-playbook -e "component=cart" roboshop.yaml
  ansible-playbook -e "component=user" roboshop.yaml
  ansible-playbook -e "component=payment" roboshop.yaml
  ansible-playbook -e "component=frontend" roboshop.yaml

