  - name: installing python setup
    import_role:
      name: common
      import_from: python_setup

  - name: create roboshop system user
    import_role:
      name: common
      import_from: app_setup

  - name: systemd setup
    import_role:
      name: common
      import_from: systemd_setup
      
  - name: enable and restart payment
    service:
      name: payment
      state: restarted
      enabled: yes
  