  - name: application setup
    import_role:
      name: common
      import_from: app_setup
  
  - name : nodejs package setup
    import_role:
      name: common
      import_from: nodejs_setup

  - name: systemd setup
    import_role:
      name: common
      import_from: systemd_setup
      
  - name: enable and restart cart
    service:
      name: cart
      state: restarted
      enabled: yes